import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
test('recommendation, persistence, backup and mobile layout use only same-origin requests', async ({ page }) => {
  const errors = [], remote = [], runtimeRequests = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => {
    if (r.url().includes('/runtime/')) runtimeRequests.push(r.url());
    if (!r.url().startsWith(new URL(process.env.SITE_URL || 'http://127.0.0.1:4173').origin)) remote.push(r.url());
  });
  await page.goto('./');
  const dataset = await (await page.request.get('./data/ssq.json')).json();
  const latest = dataset.latestIssue;
  const target = String(Number(latest) + 1);
  await expect(page.getByText(`第 ${latest} 期`, { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '生成推荐并保存' }).click();
  await expect(page.getByText(`第 ${target} 期推荐`, { exact: true })).toBeVisible({ timeout: 180000 });
  await expect(page.locator('.ticket')).toHaveCount(1);
  await page.locator('.ticket summary').click();
  await expect(page.locator('.ticket tbody tr')).toHaveCount(9);
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.reload();
  await expect(page.getByText(`第 ${target} 期推荐`, { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '数据备份', exact: true }).click();
  await page.screenshot({ path: 'test-results/backup-page.png', fullPage: true });
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载 JSON 备份' }).click();
  const backup = await download;
  await backup.saveAs('test-results/backup.json');
  const saved = JSON.parse(readFileSync('test-results/backup.json', 'utf8'));
  const reference = JSON.parse(execFileSync('python', ['scripts/reference_result.py'], { encoding: 'utf8' }));
  expect(saved.runs[0].predictions).toEqual(reference.predictions);
  await page.locator('#import').setInputFiles('test-results/backup.json');
  await expect(page.getByRole('status')).toContainText('共 1 次推荐');
  await page.getByRole('button', { name: '记录与开奖', exact: true }).click();
  await page.locator('.history > summary').click();
  await expect(page.locator('.ticket')).toHaveCount(1);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/mobile-history.png', fullPage: false });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '推荐', exact: true }).click();
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(errors).toEqual([]); expect(remote).toEqual([]); expect(runtimeRequests).toEqual([]);
});
test('legacy backup settles each run and blocks HTML injection', async ({ page }) => {
  await page.goto('./');
  const dataset = await (await page.request.get('./data/ssq.json')).json();
  const actual = dataset.draws[0];
  await page.getByRole('button', { name: '数据备份', exact: true }).click();
  await expect(page.locator('#import')).toBeEnabled({ timeout: 60000 });
  const backup = { predictions: [{ targetIssue: actual.issue, createdAt: Date.now(), modelVersion: 'auto', redBalls: actual.redBalls, blueBalls: [actual.blueBall], note: '<img src=x onerror=alert(1)>' }] };
  await page.locator('#import').setInputFiles({ name: 'android.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) });
  await expect(page.getByRole('status')).toContainText('共 1 次推荐', { timeout: 180000 });
  await page.getByRole('button', { name: '记录与开奖', exact: true }).click();
  await page.locator('.history > summary').click();
  await expect(page.locator('.settlement')).toContainText('一等奖 1 注');
  await expect(page.locator('.settlement')).toContainText('投入 ¥2');
  await page.screenshot({ path: 'test-results/settlement-page.png', fullPage: false });
  await expect(page.locator('.ticket img')).toHaveCount(0);
});
test('custom parameters are computed and identical regeneration is idempotent', async ({ page }) => {
  await page.goto('./');
  await expect(page.locator('#plan button')).toBeEnabled();
  await page.locator('[name=recentWindow]').fill('30');
  await page.locator('[name=recentWindow]').blur();
  await page.getByRole('button', { name: '生成推荐并保存' }).click();
  await expect(page.locator('.ticket')).toHaveCount(1, { timeout: process.env.SITE_URL ? 540000 : 240000 });
  await page.getByRole('button', { name: '生成推荐并保存' }).click();
  await expect(page.getByRole('status')).toContainText('方案已保存');
  await page.getByRole('button', { name: '记录与开奖', exact: true }).click();
  await expect(page.locator('.history')).toHaveCount(1);
});
